[Interface]
# A computer / Windows WireGuard client
Address = 10.66.0.2/32
PrivateKey = <A_PRIVATE_KEY>
DNS = 223.5.5.5

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = 49.232.183.40:51820
AllowedIPs = 10.66.0.0/24
PersistentKeepalive = 25
